pjt06/버전1_금융/ver1_skeleton/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/profile/', views.profile, name="profile"),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

pjt06/버전1_금융/ver1_skeleton/boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/update/', views.update, name='update'),   
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_detail, name='comment_detail'),
    path('comment/<int:comment_pk>/', views.create_reply, name='create_reply'),
    path('profile/<username>/', views.profile, name='profile'),
]

pjt06/버전1_금융/ver1_skeleton/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),
]

pjt06/버전1_금융/ver1_skeleton/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    nickname = models.CharField(max_length=30)

pjt06/버전1_금융/ver1_skeleton/boards/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Board(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments')
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

pjt06/버전1_금융/ver1_skeleton/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

# class CustomUserCreationForm(UserCreationForm):
#     class Meta:
#         # id, password, password2 만 입력받음
#         model = get_user_model()
#         fields = UserCreationForm.Meta.fields


class CustomUserCreationForm(UserCreationForm):
    # model 속성을 제외하고는 나머지는 모두 meta 클래스 내용을 그대로 가져올 때
    # 아래처럼 Meta class 도 상속받아서 써도 된다.
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

pjt06/버전1_금융/ver1_skeleton/boards/forms.py
from django import forms
from .models import Board, Comment

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ('title', 'content', )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

pjt06/버전1_금융/ver1_skeleton/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('boards:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("boards:index")
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
@require_http_methods(['POST'])
def logout(request):
    auth_logout(request)
    return redirect('boards:index')

@login_required
def follow(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)

    if person != request.user:
        if request.user in person.followers.all(): # 언팔로우
            person.followers.remove
        else: # 팔로잉
            person.followers.add(request.user)
    return redirect()

pjt06/버전1_금융/ver1_skeleton/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .models import Board, Comment
from .forms import BoardForm, CommentForm


@require_http_methods(["GET"])
def index(request):
    boards = Board.objects.all().order_by('-created_at')
    context = {
        'boards': boards
    }
    return render(request, 'boards/index.html', context)


@require_http_methods(["GET", "POST"])
def detail(request, pk):
    board = get_object_or_404(Board, pk=pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')

    comments = board.comments.all()
    comment_form = CommentForm()
    
    context = {
        'board': board,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'boards/detail.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def update(request, pk):
    board = get_object_or_404(Board, pk=pk)

    if request.method == 'POST':
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            form.save()
            return redirect('boards:detail', board.pk)
    else:
        form = BoardForm(instance=board)
    context = {
        'board': board,
        'form': form,
    }        
    return render(request, 'boards/update.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect('boards:index')
    else:
        form = BoardForm()
    context = {
        'form': form,
    }
    return render(request, 'boards/create.html', context)


@login_required
@require_http_methods(["POST"])
def comment(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.board = board
            comment.author = request.user
            comment.save()
            return redirect('boards:detail', board.pk)
        

@login_required
@require_http_methods(["POST"])
def create_reply(request, comment_pk):
    comment = get_object_or_404(Comment, id=comment_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        reply_comment = form.save(commit=False)
        reply_comment.board = comment.board
        reply_comment.author = request.user
        reply_comment.parent_comment = comment
        reply_comment.save()
        return redirect("boards:detail", comment.board.id)


@require_http_methods(["POST"])
def comment_detail(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('boards:detail', board_pk)

def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person' : person,
    }
    return render(request, 'accounts/profile.html')

pjt06/버전1_금융/ver1_skeleton/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">로그인 페이지</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-light">생성하기</button>
  </form>
</div>
{% endblock content %}

pjt06/버전1_금융/ver1_skeleton/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
<div>
  <h1>{{ person.username }}님의 프로필 페이지</h1>
  <hr>
</div>
 


  <h2>{{ person.username }}가 작성한 게시글 </h2>
{% for article in person.board_set.all %}
  <div> {{ }} </div>
{% endfor %}

{% endblock content %}

pjt06/버전1_금융/ver1_skeleton/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">회원가입 페이지</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-light">생성하기</button>
  </form>
</div>
{% endblock content %}

pjt06/버전1_금융/ver1_skeleton/boards/templates/boards/create.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">생성 페이지</h1>
  <form action="{% url 'boards:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-light">생성하기</button>
  </form>
</div>
{% endblock content %}

pjt06/버전1_금융/ver1_skeleton/boards/templates/boards/detail.html
{% extends 'base.html' %}

{% block content %}
<style>
  .custom-button {
    font-size: 5px;
    margin-top: -1rem;
  }
</style>

<div>
  <div class="d-flex justify-content-between">
    <h1 class="mb-4">상세 페이지</h1>
  </div>
  <p>글번호 : {{ board.id }}</p>  
  <p>작성자 : {{ board.author }}</p>
  <p>글제목 : {{ board.title }}</p>
  <p>글내용 : {{ board.content }}</p>
  <p>작성날짜 : {{ board.created_at }}</p>
  <p>수정날짜 : {{ board.updated_at }}</p>
  <hr>
  <div class="mb-5 d-flex justify-content-between">
    <a href="{% url 'boards:index' %}"><button class="btn btn-light">메인 페이지로</button></a>
    {% if board.author == request.user %}
    <div class="d-flex">
      <a href="{% url 'boards:update' board.id %}"><button class="me-3 btn btn-success">수정하기</button></a>
      <form action="{% url 'boards:detail' board.id%}" method='POST'>
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">삭제하기</button>
      </form>
    </div>
    {% endif %}
  </div>
  <form action="{% url 'boards:comment' board.id %}" method='POST'>
    {% csrf_token %}
    <button class="btn btn-secondary" style="float: right;" type="submit">작성하기</button>
    {{ comment_form.as_p }}
  </form>

  <div class="mt-5">
    {% if comments|length == 0 %} 댓글이 없습니다.
    {% else %}
      {% for comment in comments %}
      <div class="my-3 d-flex justify-content-between">
        <div>
          <span>{{ comment.author }} : {{ comment.content }}</span>
          <span class="mx-5">({{ comment.created_at }})</span>
        </div>
          <div>
            {% if comment.author == request.user %}
            <form action="{% url 'boards:comment_detail' board.id comment.id %}" method='POST'>
              {% csrf_token %}
              <button class="btn btn-light">삭제하기</button>
            </form>
            {% endif %}
          </div>
        </div>
        {% for reply_comment in comment.replies.all %}
          <div class="d-flex">
            <p class="ms-3" style="font-size: 5px;">{{ forloop.counter }}번째 답글 - {{ reply_comment.author }} : {{ reply_comment.content }}</p>
            {% if reply_comment.author == request.user %}
              <form class="ms-5" action="{% url 'boards:comment_detail' board.id reply_comment.id %}" method='POST'>
                {% csrf_token %}
                <button class="btn btn-light custom-button">답글 삭제하기</button>
              </form>
            {% endif %}
          </div>
        {% endfor %}
        <form class="ms-3" style="font-size: 8px;" action="{% url 'boards:create_reply' comment.id %}" method='POST'>
          {% csrf_token %}
          <button class="btn btn-secondary" style="float: right; font-size: 8px;" type="submit">답글 작성하기</button>
          {{ comment_form.as_p }}
        </form>
        <hr/>
      {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock content %}

pjt06/버전1_금융/ver1_skeleton/boards/templates/boards/index.html
{% extends 'base.html' %}

{% block content %}
<div>
  <div class="d-flex justify-content-between">
    <h1 class="mb-4">메인 페이지</h1>
    <a style="height: 70%;" href="{% url 'boards:create' %}"><button class="btn btn-info">생성하기</button></a>
  </div>
  {% if boards|length == 0 %}아직 게시글이 없습니다
  {% else %}
  {% for board in boards %}
    <p>글번호 : {{ board.id }}</p>  
    <p>작성자 : {{ board.author }}</p>
    <p>글제목 : <a href="{% url 'boards:detail' board.id %}" style="text-decoration: none;">{{ board.title }}</a></p>
    <hr>
  {% endfor %}
  {% endif %}
</div>
{% endblock content %}

pjt06/버전1_금융/ver1_skeleton/boards/templates/boards/update.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">수정 페이지</h1>
  <form action="{% url 'boards:update' board.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정하기">
  </form>
</div>
{% endblock content %}

pjt06/버전1_금융/ver1_skeleton/templates/_navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'boards:index' %}">메인 페이지</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
          <li>
            <span class="nav-link">{{ user }}</span>
          </li>
          <li>
            <a href="{% url "accounts:logout" %}" class="nav-link">로그아웃</a>
          </li>
        {% else %}
          <li>
            <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">로그인</a>
          </li>
          <li>
            <a class="nav-link" aria-current="page" href="{% url 'accounts:signup' %}">회원 가입</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

pjt06/버전1_금융/ver1_skeleton/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="mt-3 container">
    <div class="mt-3 mb-4">
      {% include '_navbar.html' %}
    </div>
    <div class="mb-5">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>